akmaier/CONRAD

src/edu/stanford/rsl/tutorial/cone/ConeBeamBackprojector.java, src/edu/stanford/rsl/tutorial/cone/ConeBeamProjector.java
Added multi-threading to CPU backprojector in tutorial/cone/ConeBeamBackprojector.java using the Reg_Key.
Fixed a small bug in the CPU version of tutorial/cone/ConeBeamProjector.java resulting in swapped detector u- and v-dimensions.
-mu
=> Bugfix and Multi-Threading in Tutorial Code

src/edu/stanford/rsl/conrad/data/numeric/NumericGridOperator.java, src/edu/stanford/rsl/conrad/data/numeric/NumericPointwiseOperators.java, src/edu/stanford/rsl/conrad/data/numeric/opencl/OpenCLBenchmark.java, src/edu/stanford/rsl/conrad/data/numeric/opencl/OpenCLGrid1D.java, src/edu/stanford/rsl/conrad/data/numeric/opencl/OpenCLGrid2D.java, src/edu/stanford/rsl/conrad/data/numeric/opencl/OpenCLGrid3D.java, src/edu/stanford/rsl/conrad/data/numeric/opencl/OpenCLGridOperators.java, src/edu/stanford/rsl/conrad/data/numeric/opencl/OpenCLGridTest.java, src/edu/stanford/rsl/conrad/data/numeric/opencl/PointwiseOperators.cl, src/edu/stanford/rsl/conrad/opencl/OpenCLUtil.java, src/edu/stanford/rsl/tutorial/iterative/GridOp.java
**Solved**
- handed in missing kernels for `log()` and `exp()` (my bad, sorry)
- fixed OpenCL grid operators initialization
- added how to use the `OpenCLGridOperators` in `OpenCLBenchmark`
- added minor improvements to `OpenCLTest.java`
- suggested transition to float all the time.
**Unsolved**
The `dotProduct` OpenCL kernel makes some trouble. In my demo `OpenCLBenchmark` it is working nicely, but not in the JUnit test. I haven't figured out, which one is wrong, the kernel or the JUnit test.
**Discussion**
Is there a reason to use both `float` and `double` in `NumericGridOperator`? In my humble opinion it is sufficient to use either `float` or `double`, not both at the same time for different methods. I am suggesting to use float by this commit.
=> Bugfix for the JUnit test and OpenCL kernels

src/edu/stanford/rsl/conrad/geometry/AbstractShape.java, src/edu/stanford/rsl/conrad/geometry/shapes/compound/CompoundShape.java, src/edu/stanford/rsl/conrad/geometry/shapes/compound/TriangleMesh.java, src/edu/stanford/rsl/conrad/geometry/shapes/simple/Triangle.java, src/edu/stanford/rsl/conrad/io/STLFileUtil.java, src/edu/stanford/rsl/conrad/physics/PhysicalObject.java, src/edu/stanford/rsl/conrad/physics/PhysicalPoint.java, src/edu/stanford/rsl/conrad/rendering/AbstractRayTracer.java, src/edu/stanford/rsl/conrad/utils/RegKeys.java
Compute the scalar product of the ray's direction and the triangle's normal vector. Assuming that all normal vectors point out of the object, we can decide whether the ray enters or leaves the object. The result is temporarily stored as another coordinate of the intersection point and later interpreted and cleaned by the ray tracer.
Allow a certain tolerance on the decision whether the intersection point of a ray with the 3-D plane lies within the triangle. This little epsilon is read from global registry.
Before:
After:
=> Removed artifacts caused by very close intersection points when creating a projection phantom of triangle meshes

src/edu/stanford/rsl/conrad/data/numeric/InterpolationOperators.java, src/edu/stanford/rsl/conrad/physics/detector/XRayDetector.java, src/edu/stanford/rsl/tutorial/cone/ConeBeamProjector.java, src/edu/stanford/rsl/tutorial/truncation/ConstantValueZeroArtifactImage.java
Changed order of arguments in addInterpolateLinear methods to familiar order, e.g. to (x, y) instead of (y, x). Checked calling methods and changed order of parameters if it seemed like the caller knew that the order was twisted. Fixes akmaier/CONRAD#12
Some comments also indicated that this would be necessary one day, e.g. *//TODO addInterpolateLinear() rows and columns are inverted*
=> Renamed and changed order of parameters of addInterpolateLinear methods

src/edu/stanford/rsl/tutorial/cone/ConeBeamBackprojector.java
These variables were the only thing that kept CONRAD from compiling with Java 7.
CONRAD should now compile without any errors using the older Java 7 or any higher version.
=> Changes variables in ConeBeamBackprojector.java to final

src/edu/stanford/rsl/tutorial/scalespace/ScaleSpaceStudies.java
The class ScaleSpaceStudies performs convolutions of projection images (sinograms) of a phantom with either a Gaussian or a Laplacian of Gaussian for different values of sigma. 
The Gaussian blurs the edges and with increasing values of sigma, the different objects with different intensities merge into one single object with one intensity. The convolution with a Gaussian containing a very small sigma subtracted from the phantom results in an image with very distinct edges.
The Laplacian of Gaussian highlights the edges with a bright and a dark line along the edges. With increasing values of sigma, the edges expand and small objects vanish.
A detailed documentation can be found as PDF file using the following link
https://www5.cs.fau.de/conrad/tutorials/api-tutorials/reconstruction/scale-sp …
=> ScaleSpaceStudies package added

src/edu/stanford/rsl/tutorial/ringArtifactCorrection/PolarConverter.java, src/edu/stanford/rsl/tutorial/ringArtifactCorrection/RingArtifactCorrectionExample.java, src/edu/stanford/rsl/tutorial/ringArtifactCorrection/RingArtifactCorrector.java
The ring artifact correction algorithm was implemented according to Prell et al. using the correction in polar coordinates. This implementation includes two classes: The PolarConverter to transform the input image (Grid2D) into polar coordinates, and the RingArtifactCorrector class that performs the actual correction. 
The code also uses the automatic object segmentation from Sijbers, J., & Postnov which removes the background/I0 regions before running the correction. The implementation might therefor fail for ROI scans. 
According to the paper from Prell et al. the code needs two filter widths: a median filtering width in radial direction and a mean filtering width in azimuthal direction. 
An example on how to use the correction is shown in RingArtifactCorrectionExample. 
The options …
=> Added ring artifact correction

data/materials/bonedense.xml, data/materials/bonelight.xml, data/materials/breastEDP.xml, data/materials/liverEDP.xml, data/materials/lungEDP.xml, data/materials/muscleEDP.xml, data/materials/omnipaque350.xml, data/materials/titaniumEDP.xml, data/materials/waterEDP.xml, src/edu/stanford/rsl/conrad/phantom/electrondensity/CrisEDPhantomGUI.java, src/edu/stanford/rsl/conrad/phantom/electrondensity/CrisEDPhantomM062.java, src/edu/stanford/rsl/conrad/phantom/electrondensity/Insert.java, src/edu/stanford/rsl/conrad/phantom/workers/MultiMaterialPhantom3DVolumeRenderer.java, src/edu/stanford/rsl/conrad/utils/RegKeys.java
Referenced "AnalyticPhantom3DVolumeRenderer.java".
Some snapshots:
=> Add "Render energy dependent attenuation" function in MultiMaterialPhantom3DVolumeRenderer

src/edu/stanford/rsl/conrad/io/NrrdFileReader.java
Nrrd File Reader now searches the direction vectors for spacing values (the vectors are not necessarily normed). Spacing is implicitly given as the L2-Norm of the direction vectors.
If the Nrrd file also includes a spacing entry, that one gets priority.
=> Changes to Nrrd File Reader: spacing from direction entry.

src/edu/stanford/rsl/conrad/opencl/backprojectCL.cl
backprojectCL.cl should not perform clamping to an edge value during backprojection.
This yields a very very bright halo outside the FOV in case of truncated objects.
This commit changes data lookups outside the FOV to return a 0 value.
=> Backprojection data lookup now performs zero-padding

src/edu/stanford/rsl/conrad/data/numeric/InterpolationOperators.java
Fixed an issue in the InterpolationOperators that would throw a Null Pointer exception when the last value (i.e. y in Grid2D, z in Grid3D) was in ]-1,0[.
If you updated your repository within the last week make sure to apply this fix.
=> Bug Fix in InterpolationOperators

src/edu/stanford/rsl/conrad/data/numeric/MultiChannelGrid3D.java, src/edu/stanford/rsl/conrad/geometry/shapes/activeshapemodels/PCA.java, src/edu/stanford/rsl/conrad/geometry/shapes/mesh/DataMatrix.java, src/edu/stanford/rsl/conrad/geometry/shapes/mesh/Mesh.java
DataMatrix: Added a getter function to return the column colIdx of the DataMatrix in its original numVertices x dimension SimpleMatrix form.
PCA: Added an applyWeights method expecting weights in the form of double[] instead of float[]. This is more consistent with projectTrainingShape() and other methods that return weights as double arrays.
Mesh: Extended to meshes featuring deformation vectors at each mesh vertex.
MultiChannelGrid3D (inherits from Grid3D): getSize() of parent class overwritten to accomodate for Grid4D member multiChannelData. Now returns the first 3 dimensions of mutliChannelData.getSize() while getNumberOfChannels() returns the 4th.
=> Minor convenience changes to DataMatrix, PCA, Mesh, and MultiChannelGrid3D. tg.

src/edu/stanford/rsl/apps/gui/XCatMetricPhantomCreator.java, src/edu/stanford/rsl/tutorial/RotationalAngiography/ResidualMotionCompensation/reconWithStreakReduction/OpenCLBackProjectorStreakReduction.java
Fixed a bug where XCatMetricPhantomCreator would yield a time of NaN if only a single phase was requested.
Fixed a bug in OpenCLBackProjectorStreakReduction where the class was erroneously shown as "OpenCL Back Projector" when configuring the Reconstruction Pipeline using the ReconstructionPipelineFrame.
=> Bug Fixes in Phantom Creator and Duplicate OpenCL Backprojector Name

src/edu/stanford/rsl/conrad/filtering/redundancy/ParkerWeightingTool.java
Added the offset computation during the calculation of the ParkerWeights.
Before, the offset has been computed and initialized only if the configure() function is called.
This is not always the case: for example if an existing Conrad.xml is loaded and the configure button is not pushed. This can cause wrong weigths and thus artifacts in the reconstructions.
=> Offset computation in ParkerWeightingTool

src/edu/stanford/rsl/conrad/geometry/trajectories/Trajectory.java
projectionMatrices Array needs a deep copy.
Former Arrays.copyOf(...) creates only a new Array but does not create new instances of containing objects.
=> Bugfix in Copy-Constructor of Trajectory class:

src/edu/stanford/rsl/conrad/phantom/xcat/BreathingScene.java
Added a user querry to BreathingScene allowing for a variable number of breathing cycles within in the scene (before: fixed as 1 cycle).
=> XCatBreathingTorso: User querry for variable number of breathing cycles

src/edu/stanford/rsl/conrad/phantom/xcat/BreathingScene.java, src/edu/stanford/rsl/conrad/phantom/xcat/CombinedBreathingHeartScene.java
Number of breathing cycles was queried for twice, if BreathingScene was part of a combined scene (e.g. Breathing+Heart). The BreathingScene constructor is now overloaded by adding a boolean to suppress the second query.
=> Fixed a bug in Breathing Scene.

src/edu/stanford/rsl/conrad/data/numeric/Grid2D.java
setSubGrid was not working since data in the buffer was not written.
Now the float[] buffer is written, which automatically takes care of the subgrid.
Unfortunately the connection/ reference between the input subGrid and the Grid2D is lost.
In other words: In case someone changes the input subGrid, which is not synchronized with Grid2D, the changes are not visible for the Grid2D.
=> setSubgrid was not working

src/edu/stanford/rsl/conrad/data/generic/complex/ComplexGrid1D.java, src/edu/stanford/rsl/conrad/data/generic/complex/ComplexGrid2D.java, src/edu/stanford/rsl/conrad/data/generic/complex/ComplexGrid3D.java
Added fftshift method to the ComplexGrid classes.
The value shift on the float buffer is applied in the 1D grid. The 2D and the 3D grid classes working on the abstract subgrid construction. 
The suggested implementation provides shift for the 1D, 2D and 3D complexGrid classes.
=> fftshift() support for ComplexGrid 1-3D classes

src/edu/stanford/rsl/conrad/data/numeric/Grid2D.java, src/edu/stanford/rsl/conrad/data/numeric/Grid4D.java, src/edu/stanford/rsl/conrad/data/numeric/MultiChannelGrid3D.java
Fixed a typo in Grid2D.
Fixed a bug in Grid4D, where setSpacing/setOrigin was not propagating the 3rd component to sub-grids.
Added setSpacing/setOrigin functionality to MultiChannelGrid3D.
=> Minor fixes to Grid classes

src/edu/stanford/rsl/conrad/io/NrrdFileReader.java
Fixed a bug in NrrdFileReader, where the origin was not written to the spatial calibration of the image.
Changed "microns" to "mm" for the moment as this seems to be the more common spacing unit.
=> Minor changes to NrrdFileReader.

src/edu/stanford/rsl/conrad/opencl/OpenCLForwardProjector.java
Fixed a bug where the mantissa of an image size product for memory allocation could not be expressed by the float data type.
Example: 379.0f *379.0f * 189.0f results in 27 148 148 when it should be 27 148 149
=> Fixed linearized image size error

src/edu/stanford/rsl/conrad/data/numeric/Grid2D.java
There was an invalid assertion in the Grid2D copy constructor.
Since the member buffer is not initialized at that point, its length is 0 and the assertion will always fail.
JUnit tests will therefore fail without reason if the program code uses this constructor.
The assertion was commented because it does not seem very useful anyway. (Put at a later position it would always pass.)
=> Fixed invalid assertion in Grid2D copy constructor

src/edu/stanford/rsl/conrad/geometry/shapes/activeshapemodels/LightPCA.java, src/edu/stanford/rsl/conrad/geometry/shapes/activeshapemodels/PCA.java
Current PCA class for active shape models stores the data matrix as a member. LightPCA discards the matrix after in-place processing in order to free memory. This is especially beneficial when working with large data matrices such as multiple 3D Deformation fields from 4D CT, if the original data is no longer needed after extracting the components.
---
Please note:
It appears that the original PCA class used for active shape models shows non-standard implementation of the eigenvalues of the covariance matrix. 
Eigenvalues are set to the signular values of the data matrix
`this.eigenValues[i] = ev[i];`
where
`double[] ev = svd.getSingularValues();`.
However, they should be set to singular values squared divided by (number of samples - 1).
While the scaling of the scores doesn't have an …
=> Memory light implementation of PCA in activeshapemodels

src/Apply_Filter.java, src/edu/stanford/rsl/conrad/filtering/opencl/BilateralFiltering3DTool.java, src/edu/stanford/rsl/conrad/filtering/opencl/Binarization2DTool.java, src/edu/stanford/rsl/conrad/filtering/opencl/Kernel3x3Filtering2DTool.java, src/edu/stanford/rsl/conrad/filtering/opencl/MeanFiltering2DTool.java, src/edu/stanford/rsl/conrad/filtering/opencl/MeanFiltering2DinGrid3DTool.java, src/edu/stanford/rsl/conrad/filtering/opencl/MeanFiltering3DTool.java, src/edu/stanford/rsl/conrad/filtering/opencl/OpenCLFilteringTool2D.java, src/edu/stanford/rsl/conrad/filtering/opencl/OpenCLFilteringTool3D.java, src/edu/stanford/rsl/conrad/filtering/opencl/binarization2D.cl, src/edu/stanford/rsl/conrad/filtering/opencl/kernel3x3Filter2D.cl, src/edu/stanford/rsl/conrad/filtering/opencl/meanFilter2D.cl, src/edu/stanford/rsl/conrad/filtering/opencl/meanFilter2DinGrid3D.cl, src/edu/stanford/rsl/conrad/filtering/opencl/meanFilter6Surrounding3D.cl
**Apply_Filter.java**
- If a filter is called from ImageJ using Plugins -> CONRAD -> Apply Filter, the available Filters are now ordered alphabetically.
- Usage of 2D and 3D OpenCL Filters was implemented/generalized
**OpenCLFilteringTool2D.java, OpenCLFilteringTool3D.java**
- Adapted class for 3D OpenCL Filtering to be more general, now more implementations can be added/used. For each implemented Filter, there is an enumeration object connecting the filter's name to its .cl-Implementation file. If a new filter is implemented, a corresponding element has to be added to this enumeration and has to be set in the constructor of the filter implementation.
- Created abstract class for 2D OpenCL Filtering with similar structure as OpenCLFilteringTool3D
**Implementations of 2D and 3D Filters …
=> Changes to OpenCL Filtering

src/edu/stanford/rsl/conrad/geometry/shapes/mesh/DataMatrix.java, src/edu/stanford/rsl/conrad/numerics/SimpleMatrix.java, src/edu/stanford/rsl/conrad/numerics/SimpleOperators.java, src/edu/stanford/rsl/conrad/numerics/SimpleVector.java
**SimpleMatrix**
now uses a linear array for its internal data buffer.
Adressing the linear buffer in 2D matrix notation is handled analogeously to the Grid2D class.
`getAtIndex(r,c) -> idx = r * this.cols + c `
These changes don't affect any methods visible from the outside. Only internal data handling is changed for memory saving purposes.
**Motivation**
Prior to this change, matrices that were far from square (i.e. rows >> cols or vice versa), would require a different amount of allocated memory depending on whether they were transposed or not.
This is due to a java handlling 2D arrays as "arrays of arrays". Thus, it takes less memory to save 2 arrays of 1000 values each (=double[2][1000]) than 1000 arrays of 2 each (=double[10000][2]).
*Minor Changes*
to SimpleVector & DataMatrix in …
=> SimpleMatrix: Changed internal buffer from double[][] to linear double[]

src/edu/stanford/rsl/conrad/utils/ImageUtil.java
ImageUtils.warpGrid returns null if called with a Grid4D, instead of simply calling wrapGrid4D.
This PR makes all pyconrad tests pass.
Btw. shouldn't this method throw instead of returning null at cases it cannot handle?
=> Extend ImageUtil.wrapGrid to handle also Grid4D

src/edu/stanford/rsl/conrad/pyconrad/PyConrad.java, src/edu/stanford/rsl/conrad/pyconrad/PythonCallback.java, src/edu/stanford/rsl/tutorial/pyconrad/PyConradExample.java, src/edu/stanford/rsl/tutorial/pyconrad/square.cpp
This PR adds Python integration to CONRAD. You can execute arbitrary Python commands from Java using the class edu.standford.rsl.conrad.pyconrad.PyConrad. Conversions NumericGrid <-> NumPy are handled automatically.
This is useful if you have an already existing Java project but need some Python or C++ routine that is not available for Java (plotting etc.). Note that you can also import C++ modules (automatic compilation). Since the magic is done by pyconrad (requires newest version) you have to launch your JVM via:
pyconrad_run --gui edu.stanford.rsl.tutorial.pyconrad.PyConradExample --dev_path /home/stephan/projects/CONRAD
The executable `pyconrad_run` should be automatically in your $PATH after installing pyconrad (it should be in the subfolder ./bin in the case of a pipenv). If …
=> Pyconrad integration

src/edu/stanford/rsl/conrad/utils/CONRAD.java, src/edu/stanford/rsl/tutorial/physics/DistributionTest.java, src/edu/stanford/rsl/tutorial/physics/NHelperFkt.java, src/edu/stanford/rsl/tutorial/physics/SingleMaterialMonteCarlo.java, src/edu/stanford/rsl/tutorial/physics/XRayAnalytics.java, src/edu/stanford/rsl/tutorial/physics/XRayTracer.java, src/edu/stanford/rsl/tutorial/physics/XRayTracerSampling.java, src/edu/stanford/rsl/tutorial/physics/XRayWorker.java, src/edu/stanford/rsl/tutorial/physics/package-info.java, src/edu/stanford/rsl/tutorial/physics/workingClass/AbstractWorker.java, src/edu/stanford/rsl/tutorial/physics/workingClass/RayWorker.java, src/edu/stanford/rsl/tutorial/physics/workingClass/TestControlUnit.java, src/edu/stanford/rsl/tutorial/physics/workingClass/VirtualPointWorker.java, src/edu/stanford/rsl/tutorial/physics/workingClass/VirtualRayWorker.java
**Major**
Finally fixed a bug, where parsing the root package was not possible when executing CONRAD from runnable JAR file.
Parsing of the list of available reconstruction filters, numerical phantom classes (etc.) now differentiates between whether CONRAD was executed from JAR or as an unpacked project.
As of V 1.1.0 (hopefully) full functionality should be established in the released *.jar version for processes that require parsing of the source tree. If you encounter any problems with the jar version, please let us know.
---
**Minor**
Some formatting changes to comply with coding guidelines in the master thesis of Tobias Miksch.
=> Potential release V 1.1.0 - Full class parsing support when executing CONRAD from *.jar

src/edu/stanford/rsl/conrad/geometry/shapes/activeshapemodels/LightPCA.java
In `reduceDimensionalityWithoutRetraining(int numComp)`:
- Comparison of numComp was reversed
- PC scores of training data was not updated
=> Fixed two bugs in latest LightPCA commit.
