akmaier/CONRAD

- src/edu/stanford/rsl/conrad/filtering/LogPoissonNoiseFilteringTool.java
- src/edu/stanford/rsl/conrad/filtering/PoissonNoiseFilteringTool.java
- src/edu/stanford/rsl/tutorial/RayByRayFilterExample.java
- src/edu/stanford/rsl/tutorial/fan/RbRFanBeamReconstructionExample.java
- src/edu/stanford/rsl/tutorial/filters/RayByRayFiltering.java
- src/edu/stanford/rsl/tutorial/phantoms/Ellipsoid.java
The Ray-by-ay filtered back projection is an algorithm that aim at reducing the noise effect in the cases of noisy FBP data. Traditionally, only a highpass filter is used e.g. ramp filter. Hence, the noise remains unaffected in the reconstructed images. The Ray-by-ray algorithm suggests modeling the projection noise on a ray-by-ray basis. The idea is to construct a set of lowpass filters of different strengths and to combine them with the traditional highpass filter. Depending on the noise variance of the ray measured, a weight is assigned. In 'CONRAD/src/edu/stanford/rsl/conrad/filtering/RayByRayFiltering.java', we implemented the algorithm based on Zeng's paper 'A filtered backprojection algorithm with ray-by-ray noise weighting'. In his paper, Zeng suggested implementing 11 frequency …
> Ray-by-ray filtering + Examples

- src/edu/stanford/rsl/conrad/data/numeric/opencl/OpenCLGridOperators.java
- src/edu/stanford/rsl/conrad/data/numeric/opencl/OpenCLGridTest.java
Fixes a memory leak in the OpenCLMotionCompensatedBackProjector class
Adds the possibility to further derive OpenCL-based motion compensated backprojectors from OpenCLMotionCompensatedBackProjector.java
Fixes compatibility issues of Matlab interaction when using Linux
> Fixes Memory Leak and Matlab Interface for Linux

- src/edu/stanford/rsl/conrad/data/numeric/BurtPyramid.java
Added the 2D Burt Image Pyramid allowing for multi-resolution processing of Grid2D.
mu
> Added 2D Burt Image Pyramid

- src/edu/stanford/rsl/conrad/data/numeric/opencl/OpenCLGridTest.java
Further change to make CONRAD finally compile with Java 1.7 or higher.
> Changes a method to improve interoperability with old Java 1.7

- data/matCon/Documentation/Matlab_Conrad_setup.txt
- data/matCon/Documentation/startup.m
Matlab integration documentation now valid for Matlab 2013b or newer
> Updates documentation on Matlab installation and usage

- src/edu/stanford/rsl/tutorial/phantoms/SimpleGridsForTruncationCorrection.java
- src/edu/stanford/rsl/tutorial/truncation/PolynomialTruncationCorrectionExample.java
Sorry for the inconvenience but we accidentally reverted merge #21 here.
Reverts akmaier/CONRAD#22
> Revert "Revert "Polynomial Truncation Correction""

- src/edu/stanford/rsl/tutorial/truncation/PolynomialTruncationCorrectionExample.java
In CT image reconstruction, the object has to be completely contained in the field of measurement of the scanner to ensure a correct reconstruction from the recorded data. However, often this ideal setup can not be achieved, e.g. with the small detectors of C-arm scanners. In these cases, the recorded sinogram will be truncated, which means that a part of the data is missing.
One approach to estimate the lost data is a polynomial truncation correction for parallel beam reconstruction. In this approach, the data is continuously extrapolated at the truncated edges of the sinogram. In the paper ‘Reconstruction from truncated projection in CT using adaptive detruncation’ Sourbelle et al. suggested to use the square root of a square function with three parameters to extrapolate the data in …
> Polynomial Truncation Correction

- src/edu/stanford/rsl/conrad/data/OpenCLMemoryDelegate.java
- src/edu/stanford/rsl/conrad/data/numeric/opencl/OpenCLGrid1D.java
- src/edu/stanford/rsl/conrad/data/numeric/opencl/OpenCLGrid2D.java
- src/edu/stanford/rsl/conrad/data/numeric/opencl/OpenCLGrid3D.java
- src/edu/stanford/rsl/conrad/geometry/Projection.java
- src/edu/stanford/rsl/tutorial/cone/ConeBeamBackProjector.cl
- src/edu/stanford/rsl/tutorial/cone/ConeBeamBackprojector.java
- src/edu/stanford/rsl/tutorial/cone/ConeBeamProjector.java
- src/edu/stanford/rsl/tutorial/cone/ConeBeamReconstructionExample.java
> Fixed scaling issues in tutorial cone beam backprojector.

- src/edu/stanford/rsl/conrad/io/SelectionCancelledException.java
- src/edu/stanford/rsl/conrad/phantom/AnalyticPhantom.java
- src/edu/stanford/rsl/conrad/phantom/AsciiSTLMeshPhantom.java
- src/edu/stanford/rsl/conrad/phantom/workers/AnalyticPhantomProjectorWorker.java
- src/edu/stanford/rsl/conrad/physics/detector/MaterialPathLengthDetector.java
- src/edu/stanford/rsl/conrad/rendering/AbstractRayTracer.java
- src/edu/stanford/rsl/conrad/rendering/WatertightRayTracer.java
- src/edu/stanford/rsl/conrad/utils/FileUtil.java
- src/edu/stanford/rsl/conrad/utils/RegKeys.java
* Removed density multiplication from material path length detector
* Added missing copyright notice
See conversation on previous pull request:
https://github.com/akmaier/CONRAD/pull/33
> Introducing the wateright ray tracer for generating projections of triangle meshes II

- src/edu/stanford/rsl/apps/gui/opengl/PointCloudViewer.java
Added more functionality for updating the point list while rendering.
> Small changes to PointCloudViewer

- src/edu/stanford/rsl/tutorial/ringArtifactCorrection/PolarConverter.java
- src/edu/stanford/rsl/tutorial/ringArtifactCorrection/RingArtifactCorrectionExample.java
- src/edu/stanford/rsl/tutorial/ringArtifactCorrection/RingArtifactCorrector.java
Addition to https://github.com/akmaier/CONRAD/pull/34
Added class and method comments as requested.
> Ring artifact correction

- src/edu/stanford/rsl/conrad/data/numeric/Grid3D.java
- src/edu/stanford/rsl/conrad/data/numeric/NumericGridOperator.java
- src/edu/stanford/rsl/conrad/data/numeric/opencl/OpenCLGridOperators.java
- src/edu/stanford/rsl/conrad/data/numeric/opencl/PointwiseOperators.cl
- src/edu/stanford/rsl/conrad/filtering/TruncationCorrectionTool.java
- src/edu/stanford/rsl/conrad/geometry/trajectories/CircularTrajectory.java
- src/edu/stanford/rsl/conrad/geometry/trajectories/HelicalTrajectory.java
- src/edu/stanford/rsl/tutorial/cone/ConeBeamBackProjector.cl
- src/edu/stanford/rsl/tutorial/cone/ConeBeamBackprojector.java
- src/edu/stanford/rsl/tutorial/cone/ConeBeamProjector.java
- src/edu/stanford/rsl/tutorial/fan/FanBeamBackProjectorPixel.cl
- src/edu/stanford/rsl/tutorial/fan/FanBeamBackProjectorRay.cl
- src/edu/stanford/rsl/tutorial/fan/FanBeamBackprojector2D.java
- src/edu/stanford/rsl/tutorial/fan/FanBeamProjector.cl
- src/edu/stanford/rsl/tutorial/fan/FanBeamProjector2D.java
- src/edu/stanford/rsl/tutorial/iterative/Etv.java
- src/edu/stanford/rsl/tutorial/iterative/IterativeReconstructionTest.java
- src/edu/stanford/rsl/tutorial/iterative/SartCL.java
- src/edu/stanford/rsl/tutorial/iterative/SartCL2D.java
Including cone and fan beam back- and forward projectors and the used arithmetic operations.
> Fully GPU-based SART and iTV implementations.

- src/edu/stanford/rsl/tutorial/scalespace/ScaleSpaceStudies.java
The class ScaleSpaceStudies performs convolutions of projection images (sinograms) of a phantom with either a Gaussian or a Laplacian of Gaussian for different values of sigma.
The Gaussian blurs the edges and with increasing values of sigma, the different objects with different intensities merge into one single object with one intensity. The convolution with a Gaussian containing a very small sigma subtracted from the phantom results in an image with very distinct edges.
The Laplacian of Gaussian highlights the edges with a bright and a dark line along the edges. Small values of sigma lead to images with sharp edges and therefore to a representation of the edge structure. With increasing values of sigma, the edges expand and small objects vanish. Large values result in the illustration …
> ScaleSpaceStudies

- src/edu/stanford/rsl/tutorial/fourierConsistency/coneBeam/Config.java
- src/edu/stanford/rsl/tutorial/fourierConsistency/coneBeam/MovementCorrection3D.java
- src/edu/stanford/rsl/tutorial/fourierConsistency/coneBeam/Test3DMovementCorrection.java
- src/edu/stanford/rsl/tutorial/fourierConsistency/coneBeam/sumFFTEnergyGradient.cl
Further documentation of the project will follow shortly.
> FourierConsistency Gradient implementation, merged with updated version by Martin 

- src/edu/stanford/rsl/apps/gui/opengl/BSplineVolumeRenderer.java
- src/edu/stanford/rsl/conrad/geometry/splines/fitting/BSplineCurveInterpolation.java
- src/edu/stanford/rsl/conrad/geometry/splines/fitting/BSplineSurfaceInterpolation.java
Added spline fitting and interpolation for curves and surfaces.
Also added a B-Spline volume renderer on OpenGL basis.
> Enhanced Spline functionality. Fitting, interpolation and rendering.

- src/edu/stanford/rsl/conrad/geometry/trajectories/Trajectory.java
Added new method to class Trajectory to compute the Isocenter (computeIsoCenterSolve), implemented by Martin Berger
> new Isocenter computation

- src/edu/stanford/rsl/conrad/geometry/shapes/simple/SwissRoll.java
In preparation of new Convex Sammon Dimensionality Reduction Package.
> SwissRoll: minor changes + doc.

- src/edu/stanford/rsl/conrad/data/numeric/NumericPointwiseOperators.java
- src/edu/stanford/rsl/tutorial/mammography/inbreast/ReadMammograms.java
- src/edu/stanford/rsl/tutorial/parallel/ParallelProjector2D.java
Small bug fixes in ParallelProjector2D and ReadMammograms, small fix in JavaDoc of NumericPointwiseOperators.
> Small bug fixes.

- src/edu/stanford/rsl/conrad/geometry/shapes/mesh/Mesh.java
Added Mesh constructor for ArrayList<PointND>
> Added Mesh constructor from ArrayList<PointND>. tg

- src/edu/stanford/rsl/conrad/geometry/shapes/activeshapemodels/kernels/GaussianKernel.java
- src/edu/stanford/rsl/conrad/geometry/splines/fitting/BSplineCurveInterpolation.java
- src/edu/stanford/rsl/conrad/geometry/splines/fitting/BSplineSurfaceInterpolation.java
Fixed missing power 2 in calculation of GaussianKernel.
Streamlining and commenting of BSpline Interpolation classes.
> Changes to Gaussian Kernel & BSpline Interpolation.

- src/edu/stanford/rsl/conrad/data/numeric/MultiChannelGrid3D.java
- src/edu/stanford/rsl/conrad/phantom/forbild/shapes/ForbildCone.java
Changed transform initialization in ForbilCone.
Added spacing and origin support for getChannel of MutliChannelGrid3D.
mu
> Small changes to ForbildCone and MultiChannelGrid3D

- src/edu/stanford/rsl/conrad/geometry/shapes/mesh/Mesh.java
- src/edu/stanford/rsl/conrad/io/VTKMeshIO.java
- VTKMeshIO can read deformations
- Mesh now uses VTKMeshIO to read meshes
tg,bb
> Streamlined mesh classes

- src/edu/stanford/rsl/conrad/geometry/transforms/Quaternion.java
functionality to determine a quaternion from a given rotation matrix
> Added functionality to quaternion class

- src/edu/stanford/rsl/conrad/geometry/motion/ArtificialMotionField.java
- src/edu/stanford/rsl/conrad/geometry/trajectories/Trajectory.java
- src/edu/stanford/rsl/conrad/opencl/OpenCLAppendBufferRenderer.java
- src/edu/stanford/rsl/conrad/opencl/OpenCLSurfacePhantomRenderer.java
- src/edu/stanford/rsl/conrad/opencl/triangleAppendBuffer.cl
- src/edu/stanford/rsl/conrad/phantom/renderer/PhantomRenderer.java
- src/edu/stanford/rsl/conrad/phantom/xcat/DynamicSquatScene.java
- src/edu/stanford/rsl/conrad/utils/RegKeys.java
Code to extract surface information from the XCAT phantom. Author: Oleksiy Rybakov.
> Surface Extraction from XCAT

- src/edu/stanford/rsl/conrad/data/numeric/InterpolationOperators.java
- src/edu/stanford/rsl/conrad/utils/ImageUtil.java
added interpolateLinear functions for Grid4D using the interpolation chain like Grid3D, Grid2D, Grid1D
> Added linear Interpolation function in InterpolationOperators for Grid4D

- src/edu/stanford/rsl/conrad/geometry/transforms/Quaternion.java
modified Quaternion.java, method: equivalentQuaternion, added error handling, made method static, corrected indices
> Quaternion class

- src/edu/stanford/rsl/conrad/opencl/OpenCLForwardProjector.java
Added option to set the configuration which volume information should be used for forward projection.
> Added configuration option

- src/edu/stanford/rsl/conrad/io/ProjectionRawIOUtil.java
Class to read and write Projection matrices that are compatible with the rigid motion creator GUI
> Add IO util for Projection Matrices

- src/edu/stanford/rsl/conrad/utils/ImageUtil.java
Local variable 'stack' was created but never used
> Remove pointless line from ImageUtils.wrapGrid4D

- src/edu/stanford/rsl/tutorial/basics/videoTutorials/tutorialASM.java
- src/edu/stanford/rsl/tutorial/modelObserver/ObserverPipeline.java
Changes:
- added simplistic code tutorial for ASMs (for MEC 2018 + video tutorials)
- minor modifications in class ObserverPipeline
> ASM tutorial

- src/edu/stanford/rsl/conrad/utils/ImageUtil.java
> Fix typo: ImageUtil.wrapGrid cannot handle Grid1D

- src/edu/stanford/rsl/conrad/utils/ImageUtil.java
Fixed a bug in ImageUtil.wrapGrid where a multi-channel grid was not recognized as such.
Changes to how calibration information is extracted in the process.
Added ImagePlus wrapGrid2D functionality for (multi-channel) Grid2D.
> Changes to ImageUtil Grid Wrappers

- src/edu/stanford/rsl/conrad/data/numeric/Grid4D.java
Java never executes assertions except if you start the VM with `-ea`.
So nobody every experienced this error.
> Fix assertion that was never run
